export { default as Character } from './Character/Character'
export { default as CharacterInfo } from './CharacterInfo/CharacterInfo'
export { default as CharactersList } from './CharactersList/CharactersList'
export { default as Comics } from './Comics/Comics'
export { default as ComicsList } from './ComicsList/ComicsList'
